/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehousesIndexRouteImport } from './routes/warehouses/index'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments/index'
import { Route as ReturnsIndexRouteImport } from './routes/returns/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as PricesIndexRouteImport } from './routes/prices/index'
import { Route as MovementsIndexRouteImport } from './routes/movements/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as ContractorsIndexRouteImport } from './routes/contractors/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProductsAddIndexRouteImport } from './routes/products/add/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesIndexRoute = WarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesIndexRoute = PricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsIndexRoute = MovementsIndexRouteImport.update({
  id: '/movements/',
  path: '/movements/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsIndexRoute = ContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAddIndexRoute = ProductsAddIndexRouteImport.update({
  id: '/products/add/',
  path: '/products/add/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/contractors': typeof ContractorsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/movements': typeof MovementsIndexRoute
  '/prices': typeof PricesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
  '/warehouses': typeof WarehousesIndexRoute
  '/products/add': typeof ProductsAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/contractors': typeof ContractorsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/movements': typeof MovementsIndexRoute
  '/prices': typeof PricesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
  '/warehouses': typeof WarehousesIndexRoute
  '/products/add': typeof ProductsAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/movements/': typeof MovementsIndexRoute
  '/prices/': typeof PricesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
  '/products/add/': typeof ProductsAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/analytics'
    | '/contractors'
    | '/employees'
    | '/movements'
    | '/prices'
    | '/products'
    | '/returns'
    | '/shipments'
    | '/warehouses'
    | '/products/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/analytics'
    | '/contractors'
    | '/employees'
    | '/movements'
    | '/prices'
    | '/products'
    | '/returns'
    | '/shipments'
    | '/warehouses'
    | '/products/add'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/analytics/'
    | '/contractors/'
    | '/employees/'
    | '/movements/'
    | '/prices/'
    | '/products/'
    | '/returns/'
    | '/shipments/'
    | '/warehouses/'
    | '/products/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  ContractorsIndexRoute: typeof ContractorsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  MovementsIndexRoute: typeof MovementsIndexRoute
  PricesIndexRoute: typeof PricesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ReturnsIndexRoute: typeof ReturnsIndexRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
  WarehousesIndexRoute: typeof WarehousesIndexRoute
  ProductsAddIndexRoute: typeof ProductsAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/': {
      id: '/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices/': {
      id: '/prices/'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/': {
      id: '/movements/'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/': {
      id: '/contractors/'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/add/': {
      id: '/products/add/'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof ProductsAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  ContractorsIndexRoute: ContractorsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  MovementsIndexRoute: MovementsIndexRoute,
  PricesIndexRoute: PricesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ReturnsIndexRoute: ReturnsIndexRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
  WarehousesIndexRoute: WarehousesIndexRoute,
  ProductsAddIndexRoute: ProductsAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
